apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operators.yaml
  - datasciencecluster.yaml
  - minio.yaml
  - model-serving.yaml
  - open-webui.yaml
  - namespaces.yaml
