apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-operators
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/<YOUR_ORG>/openshift-ai-starter.git
    targetRevision: main
    path: gitops/base/operators
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
